config/routes.rb
Rails.application.routes.draw do

    root :to => 'chat#showAll'

    get '/chat' => 'chat#showAll', as: :chats
    post '/chat/:recipient_id' => 'chat#create'
    get '/chat/:id' => 'chat#show', as: :chat
    get '/chat/send/:chat_id' => 'messages#create', as: :chat_message
    post '/chat/send/:chat_id' => 'messages#create', as: :chat_messages

    get '/user/search' => 'users#search', as: :search_user

    get '/login' => 'session#new', as: :login
    post '/login' => 'session#create'
    delete '/logout' => 'session#destroy', as: :logout

    get '/signup' => 'users#new', as: :signup
    post '/signup' => 'users#create'
    resources :users

end

app/models/chat.rb
class Chat < ActiveRecord::Base
	belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
	belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, :scope => :recipient_id

	scope :involving, -> (user) do
   		where("chats.sender_id = :id OR chats.recipient_id = :id", :id => user.id)
 	end

 	scope :between, -> (sender_id,recipient_id) do
   		where("(chats.sender_id = :sender_id AND chats.recipient_id = :recipient_id) OR (chats.sender_id = :sender_id AND chats.recipient_id = :recipient_id)", :sender_id => sender_id, :recipient_id => recipient_id)
 	end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :chat
  belongs_to :user

  validates_presence_of :body, :chat_id, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :username, presence: true
	validates :email, presence: true

	validates_uniqueness_of :username, :case_sensitive => false
	validates_uniqueness_of :email, :case_sensitive => false

	has_many :chats, :foreign_key => :sender_id

	def self.allExcept(search, user_id)
		if search && search.length > 0
			where("(username like :search OR email like :search) AND id is not :user_id", :search => "%#{search}%", :user_id => user_id)
		else
			nil
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    helper_method :current_user

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def require_user
        redirect_to '/login' unless current_user
    end

end

app/controllers/chat_controller.rb
class ChatController < ApplicationController

	before_action :require_user, only: [:showAll, :create]

	def showAll
		@chats = Chat.involving(@current_user)
	end

	def create
		if Chat.between(@current_user.id, params[:recipient_id]).present?
			@chat = Chat.between(@current_user.id, params[:recipient_id]).first
		else
			params[:sender_id] = @current_user.id
			@chat = Chat.create!(chat_params)
		end

		redirect_to chat_path(@chat)
	end

	def show
		@chat = Chat.find(params[:id])
   		@reciever = interlocutor(@chat)
   		@messages = @chat.messages
   		@message = Message.new
	end

	private
		def chat_params
			params.permit(:sender_id, :recipient_id)
		end

		def interlocutor(chat)
    		current_user == chat.recipient ? chat.sender : chat.recipient
  		end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :require_user, only: [:create]

	def create
		@chat = Chat.find(params[:chat_id])
		@message = @chat.messages.build(message_params)
		@message.user_id = @current_user.id
		@message.save!

		redirect_to chat_path(@chat)
	end

	private
		def message_params
			params.require(:message).permit(:body)
		end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

	def new
	end

	def create
		@user = User.find_by("email = :login OR username = :login", :login => params[:session][:email])
		if @user && @user.authenticate(params[:session][:password])
			session[:user_id] = @user.id
			redirect_to '/'
		else
			@errors = "error"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to '/login'
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :require_user, only: [:search]

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to '/'
		else
			render 'new'
		end
	end

	def search
		@users = User.allExcept(params[:search], @current_user.id)
	end

	private
		def user_params
			params.require(:user).permit(:username, :email, :password)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat/_submenu.html.erb
<div class="icon-bar two-up submenu" role="navigation">
	<%= link_to search_user_path, class: "item", "aria-labelledby" => "#newchat" do %>
		<label id="newchat"><i class="fi-plus"></i></label>
	<% end %>">
</div>

app/views/chat/new.html.erb
<div class="row chat">

	<div class="small-12 column">

		<h1>Start a conversation</h1>

		<%= form_for @user do |f| %>
			<%= f.label :body do %>
				<%= f.text_field :body %>
			<% end %>
		<% end %>

	</div>

</div>

<%= render 'submenu' %>

app/views/chat/show.html.erb
<div class="row chat">

	<div class="small-12 column">

		<h1><%= @reciever.username %></h1>

		<ul class="chatbox">
			<% @messages.each do |msg| %>
				<li><%= msg.body %></li>
			<% end %>
		</ul>

		<%= form_for [@chat, @message] do |f| %>
			<div class="row collapse">
				<div class="small-10 columns">
					<%= f.text_field :body, :placeholder => "Type message" %>
				</div>
				<div class="small-2 columns">
					<%= f.button "Send", class: 'button postfix fi-arrow-right' %>
				</div>
			</div>
		<% end %>

	</div>

</div>

app/views/chat/showAll.html.erb
<div class="row chats">

	<div class="small-12 column">

		<h1>Chat list</h1>

		<ul class="list">
			<% @chats.each do |chat| %>
				<li class="row collapse result">
					<%= link_to chat_path(chat) do %>
						<div class="small-1 columns">
							<i class="fi-comment"></i>
						</div>
						<div class="small-11 columns">
							<%= chat.sender.username 	unless @current_user.id == chat.sender.id %>
							<%= chat.recipient.username unless @current_user.id == chat.recipient.id %>
						</div>
					<% end %>
				</li>
			<% end %>
		</ul>

		<% if @chats.empty? %>
			<p class="panel text-center">
				<i>You don't have any conversations.</i><br>
				<%= link_to "Start a new conversation", search_user_path %>
			</p>
		<% end %>

	</div>

</div>

<%= render 'submenu' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <title><%= content_for?(:title) ? yield(:title) : "OMAD" %></title>

        <%= stylesheet_link_tag    "application" %>
        <%= javascript_include_tag "vendor/modernizr" %>
        <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>

    <body>

        <header>
            <nav>
            <% if @current_user %>
                <div class="icon-bar three-up" role="navigation">
                    <%= link_to chats_path, class: "item fi-comments", "aria-labelledby" => "#itemlabel1" do %>
                        <label id="itemlabel1">Chats</label>
                    <% end %>
                    <%= link_to nil, class: "item fi-widget", "aria-labelledby" => "#itemlabel3" do %>
                        <label id="itemlabel3">Settings</label>
                    <% end %>
                    <%= link_to logout_path, method: "delete", class: "item fi-power", "aria-labelledby" => "#itemlabel4" do %>
                        <label id="itemlabel4">Logout</label>
                    <% end %>
                </div>
            <% else %>
                <div class="icon-bar two-up" role="navigation">
                    <%= link_to login_path, class: "item fi-torso", "aria-labelledby" => "#itemlabel1" do %>
                        <label id="itemlabel1">Login</label>
                    <% end %>">
                    <%= link_to signup_path, class: "item fi-clipboard-pencil", "aria-labelledby" => "#itemlabel2" do %>
                        <label id="itemlabel2">Sign up</label>
                    <% end %>
                </div>
            <% end %>
            </nav>
        </header>

        <%= yield %>

    </body>
</html>

app/views/session/new.html.erb
<div class="row login">
	<div class="small-10 small-offset-1 column">

		<h1>Login</h1>

		<%= form_for :session, url: login_path do |f| %>

			<%= f.text_field :email, :placeholder => "Username / Email" %>
		  	<%= f.password_field :password, :placeholder => "Password" %>

			<% if @errors %>
				<small class="error">Invalid login details</small>
			<% end %>

			<%= f.submit "Log in", class: "button log-in" %>
		  	<%= link_to "Sign up", signup_path, class: "button secondary sign-up" %>

		<% end %>

	</div>
</div>

app/views/users/new.html.erb
<div class="row signup">
    <div class="form small-10 small-offset-1 column">

	    <h1>Sign up</h1>

      	<%= form_for @user, url: signup_path do |f| %>

            <div class="control">
         	  	<%= f.label :username, class: @user.errors[:username].any? ? "error" : "" do %>
                    Username <%= f.text_field :username, class: @user.errors[:username].any? ? "error" : "" %>
                <% end %>
                <% if @user.errors[:username].any? %>
                    <small class="error"><%= @user.errors[:username][0] %></small>
                <% end %>
            </div>

            <div class="control">
         	  	<%= f.label :email, class: @user.errors[:email].any? ? "error" : "" do %>
                    Email <%= f.email_field :email, class: @user.errors[:email].any? ? "error" : "" %>
                <% end %>
                <% if @user.errors[:email].any? %>
                    <small class="error"><%= @user.errors[:email][0] %></small>
                <% end %>
            </div>

            <div class="control">
         	  	<%= f.label :password, class: @user.errors[:password].any? ? "error" : "" do %>
                    Password <%= f.password_field :password, class: @user.errors[:password].any? ? "error" : "" %>
                <% end %>
                <% if @user.errors[:password].any? %>
                    <small class="error"><%= @user.errors[:password][0] %></small>
                <% end %>
            </div>

	      	<%= f.submit 'Sign up', class: 'button' %>
      	<% end %>

        <%= link_to "Already have an account?", login_path %>

    </div>
</div>

app/views/users/search.html.erb
<div class="row chat">

	<div class="small-12 column">

		<h1>Search for a person</h1>

		<%= form_tag search_user_path, :method => 'GET', :id => 'users_search' do %>
			<p>
				Find a person to start a new conversation.
			</p>
			<div class="row collapse">
				<div class="small-10 columns">
					<%= text_field_tag :search, params[:search], :placeholder => "Search by username / email" %>
				</div>
				<div class="small-2 columns">
					<%= button_tag "", class: "button postfix fi-magnifying-glass" %>
				</div>
			</div>
		<% end %>

		<% if @users %>
			<ul class="list">
				<% @users.each do |user| %>
					<li class="row collapse result">
						<%= link_to chat_path(user.id), :method => "POST" do %>
							<div class="small-1 columns">
								<i class="fi-comment"></i>
							</div>
							<div class="small-11 columns">
								<%= user.username %>
							</div>
						<% end %>
					</li>
				<% end %>
			</ul>
		<% end %>

	</div>

</div>